### ISSUE TITLE
Erratic behavior after chat close and rating

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#5]
When chat is closed the queue list is displayed (in some occasions the amount of queues in the list duplicates). When queue is selected the old conversation is continued. Correct behaviour would be to delete the user after rating is given and start a new session.

**Comment by tsavola** [comment]
Related problem: When I started the app and clicked SHOW NINCHAT!, no queues were displayed, only the Sulje ikkuna button. I clicked Sulje ikkuna, and SHOW NINCHAT! again, the queues were shown in duplicate.

**Comment by tsavola** [comment]
I repeated it. Now I have the queues in triplicate.

**Comment by JussiPekonen-Qvik** [comment]
Should be fixed now.

Note, however, that somewhat similar behavior happens when opening a PDF link on Android emulator and the browser "crashes". Why that happens remains unclear. This is most likely an emulator issue, no such issue has been observed on real devices. Therefore, I will close this issue.
